version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
      - 9101:9101
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  classification-service:
    build: classification-service
    hostname: classification-service
    container_name: classification-service
    volumes:
      - ./classification-service/:/app
    ports:
      - "5000:5000"

  data-streaming-service:
    build: data-streaming-service
    hostname: data-streaming-service
    container_name: data-streaming-service
    depends_on:
      - kafka
    volumes:
      - ./data-streaming-service/:/app

  listener-service:
    build: listener-service
    hostname: listener-service
    container_name: listener-service
    depends_on:
      - kafka
      - data-streaming-service
    volumes:
      - ./listener-service/:/app